cc_library(
  name = 'uv',
  incs = ['include'],
  export_incs = ['include'],
  srcs = [
    'src/fs-poll.c',
    'src/idna.c',
    'src/inet.c',
    'src/loop-watcher.c',
    'src/strscpy.c',
    'src/threadpool.c',
    'src/timer.c',
    'src/uv-common.c',
    'src/uv-data-getter-setters.c',
    'src/version.c',

    'src/unix/async.c',
    'src/unix/core.c',
    'src/unix/dl.c',
    'src/unix/fs.c',
    'src/unix/getaddrinfo.c',
    'src/unix/getnameinfo.c',
    'src/unix/loop.c',
    'src/unix/pipe.c',
    'src/unix/poll.c',
    'src/unix/process.c',
    'src/unix/random-devurandom.c',
    'src/unix/signal.c',
    'src/unix/stream.c',
    'src/unix/tcp.c',
    'src/unix/thread.c',
    'src/unix/tty.c',
    'src/unix/udp.c',

    'src/unix/linux-core.c',
    'src/unix/linux-inotify.c',
    'src/unix/linux-syscalls.c',
    'src/unix/procfs-exepath.c',
    'src/unix/proctitle.c',
    'src/unix/pthread-fixes.c',
    'src/unix/random-getrandom.c',
    'src/unix/random-sysctl-linux.c',
    'src/unix/sysinfo-loadavg.c',
  ],
  defs = [
    '_FILE_OFFSET_BITS=64',
    '_LARGEFILE_SOURCE',
    '_GNU_SOURCE',
    '_POSIX_C_SOURCE=200112',
  ],
  deps = [
    '#pthread',
    '#dl',
    '#rt',
  ],
)